services:
  flutter:
    build:
      context: .
    container_name: flutter_app
    volumes:
      - '/home/user/Developer:/app'
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/kvm:/dev/kvm
    network_mode: host
    environment:
      - DISPLAY=:0
    working_dir: /app
    stdin_open: true
    tty: true
    devices:
      - /dev/kvm:/dev/kvm
    privileged: true
